-- 코드를 입력하세요
# SELECT PRODUCT_NAME, PRICE
# FROM FOOD_PRODUCT
# ORDER BY PRICE DESC;

SELECT PRODUCT_ID, PRODUCT_NAME, PRODUCT_CD, CATEGORY, PRICE
FROM FOOD_PRODUCT
WHERE PRICE=(SELECT MAX(PRICE) FROM FOOD_PRODUCT)