SELECT NLI.ITEM_ID, II.ITEM_NAME, II.RARITY
FROM 
    (SELECT IT.ITEM_ID
        FROM ITEM_INFO AS II INNER JOIN ITEM_TREE AS IT
        WHERE II.RARITY="RARE"
        AND II.ITEM_ID=IT.PARENT_ITEM_ID
        AND IT.PARENT_ITEM_ID IS NOT NULL) AS NLI 
    INNER JOIN ITEM_INFO AS II
WHERE NLI.ITEM_ID=II.ITEM_ID
ORDER BY IT.ITEM_ID DESC;