-- 코드를 입력하세요
SELECT GB.TITLE, GB.BOARD_ID, GR.REPLY_ID, GR.WRITER_ID, GR.CONTENTS, DATE_FORMAT(GR.CREATED_DATE, "%Y-%m-%d") AS CREATED_DATA
FROM USED_GOODS_BOARD GB INNER JOIN USED_GOODS_REPLY GR ON GB.BOARD_ID = GR.BOARD_ID
WHERE DATE_FORMAT(GB.CREATED_DATE, "%Y%m") = "202210"
ORDER BY GR.CREATED_DATE, GB.TITLE